package br.com.ifba.curso.view;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author larissa
 */
public class CursoListar extends javax.swing.JFrame {

    /**
     * Creates new form CursoListar
     */
    public CursoListar() {
        initComponents();
        carregarTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane = new javax.swing.JScrollPane();
        tblListaCurso = new javax.swing.JTable();
        txtBuscar = new javax.swing.JTextField();
        btnEditarCurso = new javax.swing.JButton();
        btnRemoverCurso = new javax.swing.JButton();
        btnCadastrarCurso = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblListaCurso.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        tblListaCurso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", "", ""},
                {"", "", ""},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nome", "Código do curso", "Ativo"
            }
        ));
        tblListaCurso.setRowHeight(40);
        tblListaCurso.setShowHorizontalLines(true);
        tblListaCurso.setShowVerticalLines(true);
        scrollPane.setViewportView(tblListaCurso);

        getContentPane().add(scrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 760, 270));

        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 380, 50));

        btnEditarCurso.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEditarCurso.setText("Editar");
        getContentPane().add(btnEditarCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 20, 100, 50));

        btnRemoverCurso.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRemoverCurso.setText("Remover");
        btnRemoverCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverCursoActionPerformed(evt);
            }
        });
        getContentPane().add(btnRemoverCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 20, 100, 50));

        btnCadastrarCurso.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCadastrarCurso.setText("Cadastrar");
        btnCadastrarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarCursoActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastrarCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, 100, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void btnRemoverCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverCursoActionPerformed
        //Abre janela de confirmação para remoção do curso selecionado
        int resposta = JOptionPane.showConfirmDialog(
                null, 
                "Deseja apagar o curso selecionado?", 
                "Remover curso",
                JOptionPane.YES_NO_OPTION
        );
        
        //Caso a resposta seja sim, remove o curso do banco de dados
        if(resposta == JOptionPane.YES_OPTION) {
            
        }
    }//GEN-LAST:event_btnRemoverCursoActionPerformed

    private void btnCadastrarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarCursoActionPerformed
        //Abre a janela de cadastro do curso ao clicar no botão btnCadastrarCurso
        CursoCadastrar cursoCadastrar = new CursoCadastrar();
        cursoCadastrar.setVisible(true);
    }//GEN-LAST:event_btnCadastrarCursoActionPerformed

    private void carregarTabela() {
        String url = "jdbc:mysql://localhost:3306/gerenciamento_curso";
        String usuario = "root";
        String senha = "01100";
        
        //tblListaCurso.setEnabled(false);
        DefaultTableModel tabela = (DefaultTableModel) tblListaCurso.getModel();
        tabela.setNumRows(0);
        
        tblListaCurso.getColumnModel().getColumn(0);
        tblListaCurso.getColumnModel().getColumn(1);
        tblListaCurso.getColumnModel().getColumn(2);
        
        try {
            Connection conexao = DriverManager.getConnection(url, usuario, senha);
            PreparedStatement pstm;
            ResultSet rs;
            
            pstm = conexao.prepareStatement("select * from cursos;");
            rs = pstm.executeQuery();
            
            while(rs.next()) {
                tabela.addRow(new Object[]{
                    rs.getString(4),
                    rs.getString(3),
                    rs.getString(2)
                });
            }
            
            rs.close();
            pstm.close();
            conexao.close();
            
        } catch(SQLException ErroListar) {
            JOptionPane.showMessageDialog(null, "Erro ao carregar a tabela: " + ErroListar, "ERRO", JOptionPane.ERROR);
        }   
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CursoListar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CursoListar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CursoListar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CursoListar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CursoListar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarCurso;
    private javax.swing.JButton btnEditarCurso;
    private javax.swing.JButton btnRemoverCurso;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JTable tblListaCurso;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
