/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.atividade05.view;

import javax.swing.DefaultListModel;

/**
 *
 * @author larissa
 */
public class RepeticaoSlider extends javax.swing.JFrame {

    /**
     * Creates new form RepeticaoSlider
     */
    public RepeticaoSlider() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPasso = new javax.swing.JLabel();
        lblInicio = new javax.swing.JLabel();
        lblFim = new javax.swing.JLabel();
        sldPasso = new javax.swing.JSlider();
        sldInicio = new javax.swing.JSlider();
        sldFim = new javax.swing.JSlider();
        btnContar = new javax.swing.JButton();
        scrollPane = new javax.swing.JScrollPane();
        lstResultado = new javax.swing.JList<>();
        lblResultadoPasso = new javax.swing.JLabel();
        lblResultadoInicio = new javax.swing.JLabel();
        lblResultadoFim = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPasso.setText("Passo:");
        getContentPane().add(lblPasso, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 40, -1));

        lblInicio.setText("Inicio:");
        getContentPane().add(lblInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 48, 40, -1));

        lblFim.setText("Fim:");
        getContentPane().add(lblFim, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 40, -1));

        sldPasso.setMaximum(5);
        sldPasso.setMinimum(1);
        sldPasso.setValue(1);
        sldPasso.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldPassoStateChanged(evt);
            }
        });
        getContentPane().add(sldPasso, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, -1, -1));

        sldInicio.setMaximum(10);
        sldInicio.setValue(0);
        sldInicio.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldInicioStateChanged(evt);
            }
        });
        getContentPane().add(sldInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, -1, -1));

        sldFim.setMaximum(20);
        sldFim.setMinimum(11);
        sldFim.setValue(11);
        sldFim.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldFimStateChanged(evt);
            }
        });
        getContentPane().add(sldFim, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, -1, -1));

        btnContar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnContar.setText("Contar");
        btnContar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContarActionPerformed(evt);
            }
        });
        getContentPane().add(btnContar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, -1, -1));

        scrollPane.setViewportView(lstResultado);

        getContentPane().add(scrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 90, 230));

        lblResultadoPasso.setText("1");
        getContentPane().add(lblResultadoPasso, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 40, -1));

        lblResultadoInicio.setText("0");
        getContentPane().add(lblResultadoInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, 40, -1));

        lblResultadoFim.setText("11");
        getContentPane().add(lblResultadoFim, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 40, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sldInicioStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldInicioStateChanged
        // Pega o valor do sldInicio em tempo real e manda para lblResultadoInicio
        int inicio = sldInicio.getValue();
        lblResultadoInicio.setText(Integer.toString(inicio));
    }//GEN-LAST:event_sldInicioStateChanged

    private void sldFimStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldFimStateChanged
        // Pega o valor do sldFim em tempo real e manda para lblResultadoFim
        int fim = sldFim.getValue();
        lblResultadoFim.setText(Integer.toString(fim));
    }//GEN-LAST:event_sldFimStateChanged

    private void sldPassoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldPassoStateChanged
        // Pega o valor do sldPasso em tempo real e manda para lblResultadoPasso
        int passo = sldPasso.getValue();
        lblResultadoPasso.setText(Integer.toString(passo));
    }//GEN-LAST:event_sldPassoStateChanged

    private void btnContarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContarActionPerformed
        // Cria uma nova lista
        DefaultListModel resultado = new DefaultListModel();
        
        // Pega os valores dos sliders
        int inicio = sldInicio.getValue();
        int fim = sldFim.getValue();
        int passo = sldPasso.getValue();
        
        /* Usa um loop para adicionar os elementos na nova lista de acordo
        com os parâmetros escolhidos pelo usuário */
        for(int i = inicio; i <= fim; i+= passo) {
            resultado.addElement(i);
        }
        
        // Transfere os valores da lista nova para a lista original
        lstResultado.setModel(resultado);
    }//GEN-LAST:event_btnContarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RepeticaoSlider.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RepeticaoSlider.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RepeticaoSlider.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RepeticaoSlider.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RepeticaoSlider().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContar;
    private javax.swing.JLabel lblFim;
    private javax.swing.JLabel lblInicio;
    private javax.swing.JLabel lblPasso;
    private javax.swing.JLabel lblResultadoFim;
    private javax.swing.JLabel lblResultadoInicio;
    private javax.swing.JLabel lblResultadoPasso;
    private javax.swing.JList<String> lstResultado;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JSlider sldFim;
    private javax.swing.JSlider sldInicio;
    private javax.swing.JSlider sldPasso;
    // End of variables declaration//GEN-END:variables
}
